application:
  author: Edwin Maravi
  email: emaravi@cjavaperu.com
  version: 1.0.0
  title: Aplicacion SpringBoot para curso Expert 2023
  description: Aplicacion bajo arquitectura de micorservicios CJAVA 2023

config:
  security:
    oauth:
      client:
        id: cjava
        secret: "12345"
      jwt:
        key: cj
