spring:
  datasource:
    url: jdbc:mysql://localhost:3306/escuela?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  #definir dialecto mysql para hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8079